version: '3'
services:
    postgres:
        restart: always
        image: lmmdock/postgres-multi:latest
        volumes:
            - postgres-storage:/var/lib/postgres
        environment:
            - POSTGRES_DATABASES=cassiopeiadb:${CASSIOPEIA_USER}|receiptdb:${RECEIPT_USER}|datadb:${DATA_USER}
            - POSTGRES_USERS=${CASSIOPEIA_USER}:${CASSIOPEIA_PASSWORD}|${RECEIPT_USER}:${RECEIPT_PASSWORD}|${DATA_USER}:${DATA_PASSWORD}
        ports:
            - "5432:5432"
        restart: always
    
    influxdb:
        image: influxdb:latest
        ports:
            - '8086:8086'
        volumes:
            - influxdb-storage:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=cassiopeiainflux
            - INFLUXDB_USERNAME=${INFLUXDB_USER}
            - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
        restart: always
    
    #telegraf:
        #image: telegraf:latest
        #ports:
            #- '8125:8125'
        #volumes:
            #- telegraf:/var/lib/telegraf
       # links:
            #- influxdb
        #restart: always

    homeassistant:
        image: homeassistant/home-assistant:latest
        ports:
            - 8123:8123
        volumes:
            - homeassistant:/config
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        restart: always

    mosquitto:
        image: eclipse-mosquitto:1.6.13
        ports: 
            - '1883:1883'
            - '9001:9001'
        volumes:
            - mosquitto-data:/mosquitto/data
            - mosquitto-logs:/mosquitto/logs
            - mosquitto-conf:/mosquitto/config
        restart: always
    
    sensor_temp_hum:
        build: ../sensors-ha/temperature_humidity
        network_mode: host
    sensor_co2_light:
        build: ../sensors-ha/co2_light
        network_mode: host
    sensor_motion_smoke:
        build: ../sensors-ha/motion_smoke
        network_mode: host
    
    cassiopeia:
        build: ./cassiopeia
        volumes:
            - ./cassiopeia:/app
        ports:
            - "8000:80"
        command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:80"
        restart: always
    
    receipt:
        build: ../receipt-generator/receiptGenerator
        volumes:
            - ../receiptGenerator:/app
        ports:
            - "8001:81"
        command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:81"
        restart: always
    
    dataRetention:
        build: ../cassiopeia-data-retention/dataRetention
        volumes:
            - ../cassiopeia-data-retention/dataRetention:/app
        ports:
            - "8002:82"
        command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:82"
        restart: always

volumes:
    postgres-storage:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./postgres
    influxdb-storage:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./influxdb
    #telegraf:
        #driver: local
        #driver_opts:
            #o: bind
            #type: none
            #device: ./telegraf
    homeassistant:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./homeassistant
    mosquitto-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./mosquitto/mosquittodata
    mosquitto-logs:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./mosquitto/mosquittologs
    mosquitto-conf:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./mosquitto/mosquittoconfig