version: '3'
services:
    postgres_cassiopeia:
        restart: always
        image: lmmdock/postgres-multi:latest
        volumes:
            - postgres-storage:/var/lib/postgres
        environment:
            - POSTGRES_DATABASES=cassiopeiadb:${CASSIOPEIA_USER}|receiptdb:${RECEIPT_USER}|datadb:${DATA_USER}
            - POSTGRES_USERS=${CASSIOPEIA_USER}:${CASSIOPEIA_PASSWORD}|${RECEIPT_USER}:${RECEIPT_PASSWORD}|${DATA_USER}:${DATA_PASSWORD}
        ports:
            - "5432:5432"
        restart: always

    cassiopeia:
        build: ./cassiopeia
        volumes:
            - ./cassiopeia:/app
        ports:
            - "8000:80"
        command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:80"
        restart: always
    
    homeassistant:
        image: homeassistant/home-assistant:latest
        ports:
            - 8123:8123
        volumes:
            - homeassistant:/config
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        restart: always

    mosquitto:
        image: eclipse-mosquitto:1.6.13
        ports: 
            - '1883:1883'
            - '9001:9001'
        volumes:
            - mosquitto-data:/mosquitto/data
            - mosquitto-logs:/mosquitto/logs
            - mosquitto-conf:/mosquitto/config
        restart: always
    


volumes:
    postgres-storage:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./postgres
    homeassistant:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./homeassistant
    mosquitto-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./mosquitto/mosquittodata
    mosquitto-logs:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./mosquitto/mosquittologs
    mosquitto-conf:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./mosquitto/mosquittoconfig