# Generated by Django 3.1.7 on 2021-03-11 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Policy',
            fields=[
                ('policyid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('policy', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Create_User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
