# Generated by Django 3.1.7 on 2021-03-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Policy',
            fields=[
                ('policyid', models.AutoField(primary_key=True, serialize=False)),
                ('policy', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Create_User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('datein', models.DateField()),
                ('dateout', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Device_Create',
            fields=[
                ('deviceid', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.create_user')),
                ('policyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.create_policy')),
            ],
        ),
        migrations.CreateModel(
            name='Consent_Reply',
            fields=[
                ('consentid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consent', models.BooleanField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.create_user')),
                ('policyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.create_policy')),
            ],
        ),
    ]
