# Generated by Django 3.1.7 on 2021-07-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entityid', models.AutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=100)),
                ('policyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.policy')),
            ],
        ),
    ]
