# Generated by Django 3.1.7 on 2021-07-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceid', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Create_Policy',
            new_name='Policy',
        ),
        migrations.DeleteModel(
            name='Device_Create',
        ),
        migrations.AddField(
            model_name='device',
            name='policyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.policy'),
        ),
    ]
