# Generated by Django 3.1.7 on 2021-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_policy',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
