# Generated by Django 3.1.7 on 2021-08-25 16:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='state',
            field=models.CharField(choices=[(app.models.State['av'], 'Available'), (app.models.State['re'], 'Requested'), (app.models.State['de'], 'Deleted')], default=app.models.State['av'], max_length=16),
        ),
    ]
