# Generated by Django 3.1.7 on 2021-07-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210724_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_user',
            name='datein',
        ),
        migrations.RemoveField(
            model_name='create_user',
            name='dateout',
        ),
    ]
