# Generated by Django 3.1.7 on 2021-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210724_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datein', models.DateField()),
                ('dateout', models.DateField()),
            ],
        ),
    ]
