# Generated by Django 3.1.7 on 2021-07-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_create_stay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('consentid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consent', models.BooleanField()),
                ('deviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datein', models.DateField()),
                ('dateout', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consent_reply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='consent_reply',
            name='policyid',
        ),
        migrations.DeleteModel(
            name='Create_Stay',
        ),
        migrations.RenameModel(
            old_name='Create_User',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Consent_Reply',
        ),
        migrations.AddField(
            model_name='stay',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
